name: Proofline

services:
  redis:
    image: redis:8-alpine
    container_name: proofline_redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    networks:
      - proofline_network

  mysql:
    image: mysql
    container_name: proofline_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proofline_db
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - proofline_network

networks:
  proofline_network:
    driver: bridge
