name: Proofline

services:
  redis:
    image: redis:8-alpine
    container_name: proofline_redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    networks:
      - proofline_network

networks:
  proofline_network:
    driver: bridge
